version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d nestjs" ]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: "5432"
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: nestjs
      DB_SYNC: "true"
      SEED_ON_BOOT: "true"
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT:-3000}
    ports:
      - "3000:3000"

volumes:
  db_data:
